### ISSUE TITLE
Fix workers

### ISSUE THREAD

**Issue by stwiname** [subquery/subql-algorand#46]
Workers not working:

```
"level":"error","timestamp":"2023-05-25T23:08:38.983Z","pid":7,"hostname":"subquery-18141-indexer-deployment-86f445f558-hcldh","category":"nestjs-#4","payload":"[{\"trace\":\"1\"},\"TypeError: this.eventEmitter.emit is not a function\\n    at /usr/local/lib/node_modules/@subql/node-algorand/dist/algorand/api.service.algorand.js:45:31\\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\\n    at async Promise.all (index 0)\\n    at async AlgorandApiService.init (/usr/local/lib/node_modules/@subql/node-algorand/dist/algorand/api.service.algorand.js:42:29)\\n    at async InstanceWrapper.useFactory [as metatype] (/usr/local/lib/node_modules/@subql/node-algorand/dist/indexer/indexer.module.js:38:21)\\n    at async Injector.instantiateClass (/usr/local/lib/node_modules/@subql/node-algorand/node_modules/@nestjs/core/injector/injector.js:334:37)\\n    at async callback (/usr/local/lib/node_modules/@subql/node-algorand/node_modules/@nestjs/core/injector/injector.js:48:30)\\n    at async Injector.resolveConstructorParams (/usr/local/lib/node_modules/@subql/node-algorand/node_modules/@nestjs/core/injector/injector.js:122:24)\\n    at async Injector.loadInstance (/usr/local/lib/node_modules/@subql/node-algorand/node_modules/@nestjs/core/injector/injector.js:52:9)\\n    at async Injector.loadProvider (/usr/local/lib/node_modules/@subql/node-algorand/node_modules/@nestjs/core/injector/injector.js:74:9)\"]","message":"this.eventEmitter.emit is not a function"}
{"level":"error","timestamp":"2023-05-25T23:08:39.007Z","pid":7,"hostname":"subquery-18141-indexer-deployment-86f445f558-hcldh","category":"worker: 4","message":"Worker exited with code 1"
```

**Comment by stwiname** [comment]
Fixed in https://github.com/subquery/subql-algorand/pull/47
